### ISSUE TITLE
FAF Instant crash (no lobby) unable to create effect: (...)\effects.nx2\effects\range.fx

### ISSUE THREAD

**Issue by Frozen-byte** [FAForever/faf-linux#14]
Heyho, I recently updated my Linux to Ubuntu 23.04 and now FAF-Client does not launch the game anymore.
This is a cross-post from https://forum.faforever.com/topic/6001/faf-instant-crash-no-lobby-unable-to-create-effect-effects-nx2-effects-range-fx I will keep them in sync.

Playing via Steam works fine, only when I try to host/watch/ladder a game via FAF the Game instantly crashes. Last (and I guess relevant) log:

```
info: Compiled shader: /effects/primbatcher.fx
warning: z:\home\%USER%\.faforever\gamedata\effects.nx2\effects\range.fx: unable to create effect: z:\home\%USER%\.faforever\gamedata\effects.nx2\effects\range.fx reason: unknown error
```
What I have tried so far:

1. Reinstalled FAF and SupCom completely
2. `sudo apt install git wget jq cabextract libxcomposite1:amd64 libxcomposite1:i386 libfreetype6:amd64 libfreetype6:i386` tells me everything is installed on lates version.
3. Used protonwrapper 'GE-55' and 'SteamExperimental'
4. Sometimes, it crashes at `primbatcher.fx`, somtimes at `sky.fx` but its always in proximitry to `range.fx`

**Comment by UTFTymoteusz** [comment]
I'm getting the same issues on Arch.

**Comment by nikolaevigor** [comment]
same on manjaro

**Comment by iczero** [comment]
Collected solutions from [the discord thread](https://discord.com/channels/197033481883222026/1098774035925577769), in no particular order:

- In `launchwrapper`, add `/windowed 1920 1080` at the end of the last line (the one beginning with `exec`)
- Export the environment variable `DXVK_STATE_CACHE=disable` before `./run` (i.e. `DXVK_STATE_CACHE=disable ./run`)
- Export `DXVK_STATE_CACHE=reset` instead
- Delete the dxvk cache file in `dxvk-cache/`
- Update dxvk to a newer version (`./update-component.sh dxvk 2.2`, replacing `2.2` with another version)
- Switch to another GPU vendor

I have not had much time to work on this recently, and I apologize for that. These solutions have _sometimes_ worked for various people and may not work for you. If you have found another way, please post it here or in the discord thread.

**Comment by iczero** [comment]
I haven't had any reports of similar issues for a while now. Hopefully the problem was fixed in a driver update or similar. Closing.
