### ISSUE TITLE
Crashing whenever I create game

### ISSUE THREAD

**Issue by E-daw** [FAForever/faf-linux#18]
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x6658d419
    attempted to read memory at 0x11216000

Program : Z:\home\wade\.faforever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log /home/wade/.faforever/logs/game_20446834.log /gpgnet 127.0.0.1:35989 /mean 1473.08 /deviation 444.318 /savereplay gpgnet://127.0.0.1:46215/20446834/edaw.SCFAreplay /country US /numgames 10 /numgames 2

Callstack:
	Unknown symbol (address 0x6658d419)
	Unknown symbol (address 0x6658e17e)
	Unknown symbol (address 0x66586ffe)
	Unknown symbol (address 0x66584182)
	Unknown symbol (address 0x004da9f6)

Last 100 lines of log...

info: IsStreamingWaveBank("/sounds/unitsglobal.xwb") => false
debug: SND: Loaded WaveBank 'unitsglobal' at 5956088
info: IsStreamingWaveBank("/sounds/ura.xwb") => false
debug: SND: Loaded WaveBank 'ura' at 5956128
info: IsStreamingWaveBank("/sounds/uradestroy.xwb") => false
debug: SND: Loaded WaveBank 'uradestroy' at 59561c8
info: IsStreamingWaveBank("/sounds/uraweapon.xwb") => false
debug: SND: Loaded WaveBank 'uraweapon' at 5956268
info: IsStreamingWaveBank("/sounds/urb.xwb") => false
debug: SND: Loaded WaveBank 'urb' at 5956308
info: IsStreamingWaveBank("/sounds/url.xwb") => false
debug: SND: Loaded WaveBank 'url' at 59563a8
info: IsStreamingWaveBank("/sounds/urldestroy.xwb") => false
debug: SND: Loaded WaveBank 'urldestroy' at 5957fa8
info: IsStreamingWaveBank("/sounds/urlweapon.xwb") => false
debug: SND: Loaded WaveBank 'urlweapon' at 5958048
info: IsStreamingWaveBank("/sounds/urs.xwb") => false
debug: SND: Loaded WaveBank 'urs' at 59580e8
info: IsStreamingWaveBank("/sounds/ursdestroy.xwb") => true
debug: SND: Loaded WaveBank 'ursdestroy' at 59581a8
info: IsStreamingWaveBank("/sounds/ursstream.xwb") => true
debug: SND: Loaded WaveBank 'ursstream' at 5958288
info: IsStreamingWaveBank("/sounds/ursweapon.xwb") => false
debug: SND: Loaded WaveBank 'ursweapon' at 5958328
info: IsStreamingWaveBank("/sounds/xaa_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xaa_weapon' at 596b0a8
info: IsStreamingWaveBank("/sounds/xab.xwb") => false
debug: SND: Loaded WaveBank 'xab' at 596b168
info: IsStreamingWaveBank("/sounds/xal.xwb") => false
debug: SND: Loaded WaveBank 'xal' at 596b228
info: IsStreamingWaveBank("/sounds/xal_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xal_weapon' at 596b2e8
info: IsStreamingWaveBank("/sounds/xas.xwb") => false
debug: SND: Loaded WaveBank 'xas' at 596b388
info: IsStreamingWaveBank("/sounds/xas_weapons.xwb") => false
debug: SND: Loaded WaveBank 'xas_weapons' at 596bc28
info: IsStreamingWaveBank("/sounds/xea.xwb") => false
debug: SND: Loaded WaveBank 'xea' at 596bcc8
info: IsStreamingWaveBank("/sounds/xea_weapons.xwb") => false
debug: SND: Loaded WaveBank 'xea_weapons' at 596bd88
info: IsStreamingWaveBank("/sounds/xeb.xwb") => false
debug: SND: Loaded WaveBank 'xeb' at 596be48
info: IsStreamingWaveBank("/sounds/xel.xwb") => false
debug: SND: Loaded WaveBank 'xel' at 596bee8
info: IsStreamingWaveBank("/sounds/xel_weapons.xwb") => false
debug: SND: Loaded WaveBank 'xel_weapons' at 596bfa8
info: IsStreamingWaveBank("/sounds/xes.xwb") => false
debug: SND: Loaded WaveBank 'xes' at 596ccc8
info: IsStreamingWaveBank("/sounds/xes_destroy.xwb") => true
debug: SND: Loaded WaveBank 'xes_destroy' at 596cda8
info: IsStreamingWaveBank("/sounds/xes_weapons.xwb") => false
debug: SND: Loaded WaveBank 'xes_weapons' at 596ce48
info: IsStreamingWaveBank("/sounds/xra.xwb") => false
debug: SND: Loaded WaveBank 'xra' at 596cf08
info: IsStreamingWaveBank("/sounds/xra_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xra_weapon' at 596cfc8
info: IsStreamingWaveBank("/sounds/xrb.xwb") => false
debug: SND: Loaded WaveBank 'xrb' at 5976920
info: IsStreamingWaveBank("/sounds/xrl.xwb") => false
debug: SND: Loaded WaveBank 'xrl' at 59769c0
info: IsStreamingWaveBank("/sounds/xrl_stream.xwb") => true
debug: SND: Loaded WaveBank 'xrl_stream' at 5976a80
info: IsStreamingWaveBank("/sounds/xrl_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xrl_weapon' at 5976b20
info: IsStreamingWaveBank("/sounds/xrs.xwb") => false
debug: SND: Loaded WaveBank 'xrs' at 5976be0
info: IsStreamingWaveBank("/sounds/xrs_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xrs_weapon' at 5976ca0
info: IsStreamingWaveBank("/sounds/xsa.xwb") => false
debug: SND: Loaded WaveBank 'xsa' at 5980078
info: IsStreamingWaveBank("/sounds/xsa_destroy.xwb") => false
debug: SND: Loaded WaveBank 'xsa_destroy' at 5980118
info: IsStreamingWaveBank("/sounds/xsa_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xsa_weapon' at 59801b8
info: IsStreamingWaveBank("/sounds/xsb.xwb") => false
debug: SND: Loaded WaveBank 'xsb' at 5980258
info: IsStreamingWaveBank("/sounds/xsb_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xsb_weapon' at 59802f8
info: IsStreamingWaveBank("/sounds/xsl.xwb") => false
debug: SND: Loaded WaveBank 'xsl' at 5980398
info: IsStreamingWaveBank("/sounds/xsl_destroy.xwb") => false
debug: SND: Loaded WaveBank 'xsl_destroy' at 59823c0
info: IsStreamingWaveBank("/sounds/xsl_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xsl_weapon' at 5982460
info: IsStreamingWaveBank("/sounds/xss.xwb") => false
debug: SND: Loaded WaveBank 'xss' at 5982500
info: IsStreamingWaveBank("/sounds/xss_destroy.xwb") => true
debug: SND: Loaded WaveBank 'xss_destroy' at 59825e0
info: IsStreamingWaveBank("/sounds/xss_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xss_weapon' at 5982680
debug: SND: Loaded SoundBank 'ambienttest'
debug: SND: Loaded SoundBank 'explosions'
debug: SND: Loaded SoundBank 'fmv_bg'
debug: SND: Loaded SoundBank 'impacts'
debug: SND: Loaded SoundBank 'interface'
debug: SND: Loaded SoundBank 'music'
debug: SND: Loaded SoundBank 'op_briefing'
debug: SND: Loaded SoundBank 'seraphimselect'
debug: SND: Loaded SoundBank 'uaa'
debug: SND: Loaded SoundBank 'uaadestroy'

I'm not sure at all what's causing this and I couldn't find any helpful information on the matter. This happens everytime I try to create a game or watch a replay. It only occurs when I use the launcher, I'm able to play the game through steam without issue.

**Comment by E-daw** [comment]
Fixed the issue by installing Protontricks

**Comment by LichHunter** [comment]
Hi sorry for writing to closed issue but @E-daw  could you please provide command that helped you to fix issued cause I'm facing something similar and use this command `protontricks 9420 dlls d3dx9 xact` from faf wiki did not help me
Thank you

Logs
`
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x6658d432
    attempted to read memory at 0x11459000

Program : Z:\home\omen\.faforever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log /home/omen/.faforever/logs/game_20738054.log /gpgnet 127.0.0.1:33159 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:37211/20738054/Tyzzantith_Life_.SCFAreplay /country PL /numgames 0 /numgames 0

Callstack:
	Unknown symbol (address 0x6658d432)
	Unknown symbol (address 0x6658e17e)
	Unknown symbol (address 0x66586ffe)
	Unknown symbol (address 0x66584182)
	Unknown symbol (address 0x004da9f6)

Last 100 lines of log...

debug: SND: Loaded WaveBank 'xrl_weapon' at 5eeb468
info: IsStreamingWaveBank("/sounds/xrs.xwb") => false
debug: SND: Loaded WaveBank 'xrs' at 5eeb528
info: IsStreamingWaveBank("/sounds/xrs_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xrs_weapon' at 5eeb5e8
info: IsStreamingWaveBank("/sounds/xsa.xwb") => false
debug: SND: Loaded WaveBank 'xsa' at 5ef4fa8
info: IsStreamingWaveBank("/sounds/xsa_destroy.xwb") => false
debug: SND: Loaded WaveBank 'xsa_destroy' at 5ef5048
info: IsStreamingWaveBank("/sounds/xsa_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xsa_weapon' at 5ef50e8
info: IsStreamingWaveBank("/sounds/xsb.xwb") => false
debug: SND: Loaded WaveBank 'xsb' at 5ef5188
info: IsStreamingWaveBank("/sounds/xsb_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xsb_weapon' at 5ef5228
info: IsStreamingWaveBank("/sounds/xsl.xwb") => false
debug: SND: Loaded WaveBank 'xsl' at 5ef52c8
info: IsStreamingWaveBank("/sounds/xsl_destroy.xwb") => false
debug: SND: Loaded WaveBank 'xsl_destroy' at 5ef7508
info: IsStreamingWaveBank("/sounds/xsl_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xsl_weapon' at 5ef75a8
info: IsStreamingWaveBank("/sounds/xss.xwb") => false
debug: SND: Loaded WaveBank 'xss' at 5ef7648
info: IsStreamingWaveBank("/sounds/xss_destroy.xwb") => true
debug: SND: Loaded WaveBank 'xss_destroy' at 5ef7728
info: IsStreamingWaveBank("/sounds/xss_weapon.xwb") => false
debug: SND: Loaded WaveBank 'xss_weapon' at 5ef77c8
debug: SND: Loaded SoundBank 'ambienttest'
debug: SND: Loaded SoundBank 'explosions'
debug: SND: Loaded SoundBank 'fmv_bg'
debug: SND: Loaded SoundBank 'impacts'
debug: SND: Loaded SoundBank 'interface'
debug: SND: Loaded SoundBank 'music'
debug: SND: Loaded SoundBank 'op_briefing'
debug: SND: Loaded SoundBank 'seraphimselect'
debug: SND: Loaded SoundBank 'tm_aeonweapons'
debug: SND: Loaded SoundBank 'tm_aircrafts'
debug: SND: Loaded SoundBank 'tm_cybranweapons'
debug: SND: Loaded SoundBank 'tm_explosions'
debug: SND: Loaded SoundBank 'tm_robotsounds'
debug: SND: Loaded SoundBank 'tm_uefweapons'
debug: SND: Loaded SoundBank 'tmmm_cues'
debug: SND: Loaded SoundBank 'uaa'
debug: SND: Loaded SoundBank 'uaadestroy'
debug: SND: Loaded SoundBank 'uaaweapon'
debug: SND: Loaded SoundBank 'uab'
debug: SND: Loaded SoundBank 'ual'
debug: SND: Loaded SoundBank 'ualdestroy'
debug: SND: Loaded SoundBank 'ualweapon'
debug: SND: Loaded SoundBank 'uas'
debug: SND: Loaded SoundBank 'uasdestroy'
debug: SND: Loaded SoundBank 'uasweapon'
debug: SND: Loaded SoundBank 'uea'
debug: SND: Loaded SoundBank 'ueadestroy'
debug: SND: Loaded SoundBank 'ueaweapon'
debug: SND: Loaded SoundBank 'ueb'
debug: SND: Loaded SoundBank 'uel'
debug: SND: Loaded SoundBank 'ueldestroy'
debug: SND: Loaded SoundBank 'uelweapon'
debug: SND: Loaded SoundBank 'ues'
debug: SND: Loaded SoundBank 'uesdestroy'
debug: SND: Loaded SoundBank 'uesweapon'
debug: SND: Loaded SoundBank 'unitrumble'
debug: SND: Loaded SoundBank 'unitsglobal'
debug: SND: Loaded SoundBank 'ura'
debug: SND: Loaded SoundBank 'uradestroy'
debug: SND: Loaded SoundBank 'uraweapon'
debug: SND: Loaded SoundBank 'urb'
debug: SND: Loaded SoundBank 'url'
debug: SND: Loaded SoundBank 'urldestroy'
debug: SND: Loaded SoundBank 'urlweapon'
debug: SND: Loaded SoundBank 'urs'
debug: SND: Loaded SoundBank 'ursdestroy'
debug: SND: Loaded SoundBank 'ursstream'
debug: SND: Loaded SoundBank 'ursweapon'
debug: SND: Loaded SoundBank 'xaa'
debug: SND: Loaded SoundBank 'xaa_weapon'
debug: SND: Loaded SoundBank 'xab'
debug: SND: Loaded SoundBank 'xal'
debug: SND: Loaded SoundBank 'xal_weapon'
debug: SND: Loaded SoundBank 'xas'
debug: SND: Loaded SoundBank 'xas_weapon'
debug: SND: Loaded SoundBank 'xca'
debug: SND: Loaded SoundBank 'xcb'
debug: SND: Loaded SoundBank 'xcl'
debug: SND: Loaded SoundBank 'xcs'
debug: SND: Loaded SoundBank 'xea'
debug: SND: Loaded SoundBank 'xea_weapon'
debug: SND: Loaded SoundBank 'xeb'
debug: SND: Loaded SoundBank 'xel'
debug: SND: Loaded SoundBank 'xel_weapons'
debug: SND: Loaded SoundBank 'xes'
debug: SND: Loaded SoundBank 'xes_destroy'
debug: SND: Loaded SoundBank 'xes_weapons'
debug: SND: Loaded SoundBank 'xra'
debug: SND: Loaded SoundBank 'xra_weapon'
debug: SND: Loaded SoundBank 'xrb'
debug: SND: Loaded SoundBank 'xrl'
debug: SND: Loaded SoundBank 'xrl_destroy'
debug: SND: Loaded SoundBank 'xrl_stream'
`

**Comment by Ansgar2000** [comment]
> Fixed the issue by installing Protontricks

And how?
