### ISSUE TITLE
Ubuntu snap usage

### ISSUE THREAD

**Issue by CyberMinion** [FAForever/faf-linux#23]
Hello, 

For unfortunate reasons I won't get into, I'm stuck with the Ubuntu's snap of Steam. It seems this script doesn't recognize that, and although I've added the path to the snap Steam install, it isn't happy.

steamapps is located here:
`/snap/steam/common/.local/share/Steam/steamapps`
But the file this script is looking for, `/steamapps/libraryfolders.vdf` is not present there. For that matter, I don't think that file exists anywhere...

Is there an easy way to make this work, without just removing that check and trying to force the script to continue anyway? Or is that exactly what I need to do?

Thanks!

**Comment by iczero** [comment]
Hi, sorry for the late reply. `libraryfolders.vdf` is usually present in `~/.local/share/Steam/steamapps/libraryfolders.vdf`. Can you check if it is in `~/snap/steam/common/.local/share/Steam/steamapps/libraryfolders.vdf` or somewhere similar?

**Comment by iczero** [comment]
If you're still having this problem, please reopen the issue.
