### ISSUE TITLE
Need to do matchmaking BEFORE custom game

### ISSUE THREAD

**Issue by hansbogert** [FAForever/faf-linux#25]
Tried to start a custom game, but constantly hit:

> 0024:err:module:import_dll Loading library d3dx9_35.dll (which is needed by L"Z:\\home\\gandalf\\.faforever\\bin\\ForgedAlliance.exe") failed (error c000012f).
0024:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\gandalf\\.faforever\\bin\\ForgedAlliance.exe" failed, status c0000135

after a couple of reinstall retries tried a matchmaking game first, and then it installed some more files it seemed. Afterwards, custom games started to work fine

**Comment by iczero** [comment]
Can you please retry with the latest commit?
