### ISSUE TITLE
dxvk 2.0 crashes immediately after loading screen

### ISSUE THREAD

**Issue by iczero** [FAForever/faf-linux#3]
> Unfortunately, the Skirmish game crashes after the loading screen. Have no idea what to do

_Originally posted by @Wondertan in https://github.com/FAForever/faf-linux/issues/1#issuecomment-1312549986_

This appears to be caused by upgrading to dxvk 2.0.

**Comment by iczero** [comment]
Upstream issue filed, see https://github.com/doitsujin/dxvk/issues/3058

**Comment by iczero** [comment]
dxvk v2.1 removes the setup script. This needs to be rewritten.

**Comment by p4block** [comment]
You can copy the install script from 2.0, works no problem, but iirc there's another way of installing it not involving the script

**Comment by iczero** [comment]
Fixed in https://github.com/FAForever/faf-linux/commit/0e1c146a4f9839a2dba5b10f26153b9010c64d8c
