### ISSUE TITLE
had to also use `PROTON_USE_WINED3D=1`

### ISSUE THREAD

**Issue by MartenBE** [FAForever/faf-linux#36]
https://github.com/FAForever/faf-linux/blob/776f7bddf9000ef6b152ff78187017eca0a81e72/README.md?plain=1#L47

I had to also use `PROTON_USE_WINED3D=1` otherwise I just get a black screen with a grey box when starting up the game.

![Screenshot_20240416_165154](https://github.com/FAForever/faf-linux/assets/1958780/fe2d683c-b00d-4df1-87c6-4f59f948bb8a)

Used parameters to fix: `PROTON_USE_WINED3D=1 PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%`

**Comment by MartenBE** [comment]
After setting these parameters in steam, I can start the game from steam (vanilla). But from within the client, I still get the grey box screen from above ...

**Comment by iczero** [comment]
Please do not use WineD3D, it will cause significant performance degradation and many effects may not properly render.

Can you try appending `/fullscreen <xres> <yres>` in the client launch options, similar to the following screenshot:

![image-1.png](https://github.com/FAForever/faf-linux/assets/10750302/1e9d58fe-94f4-402c-b505-8522f0a081d3)

**Comment by MartenBE** [comment]
That did the trick! (on my 4k system I had to adjust it to `/fullscreen 3840 2160`)
Thank you very much for this repo, it is a lifesaver! :)

**Comment by iczero** [comment]
@Goury Please do not comment on old issues unless you have further details to add.
