### ISSUE TITLE
Flatpak Steam

### ISSUE THREAD

**Issue by TheFloatingBrain** [FAForever/faf-linux#4]
I was wondering if FAF can be installed when using the flatpak version of steam (and in turn SC:FA)

**Comment by tatsujb** [comment]
@TheFloatingBrain I would strongly recommend not doing that. (even if you don't encounter issues running FAF and FA, I've encountered issues running other games through proton on a steam that was installed via flatpak, but of course, you are free to try. did it work in your case?)

**Comment by iczero** [comment]
This is currently a supported configuration.
