### ISSUE TITLE
2024.6.0 is not Updating

### ISSUE THREAD

**Issue by veqqq** [FAForever/faf-linux#44]
It's locked on 2024.5.0 but the server requires a newer version. Perform says all is up to date.

**Comment by iczero** [comment]
Maybe I should just have it pull versions from upstream...

**Comment by iczero** [comment]
Can you please try update again?

https://github.com/FAForever/faf-linux/commit/166f388609881cf15ab80a4f98bb05dfaeeb08c8

**Comment by veqqq** [comment]
Perfect!

Also, just wow. That's... Beyond fast. No other software project, opensource or with expensive support and high SLAs has such fast turn arounds. Thank you so much!
