### ISSUE TITLE
Bug in OpenSUSE

### ISSUE THREAD

**Issue by Who-are-me** [FAForever/faf-linux#45]
Not find installed libs for OpenSUSE, please fix it

**Comment by iczero** [comment]
Please attach logs.

Did you install the 32-bit libraries?

**Comment by Who-are-me** [comment]
Its work, i just coment lines [126..150], all library installed
![Screenshot_20240714_135923](https://github.com/user-attachments/assets/118c2b45-2c01-44aa-b6fd-b4e1b2f8a7a2)

**Comment by Who-are-me** [comment]
bug for example
![Screenshot_20240714_140135](https://github.com/user-attachments/assets/5e308e7f-cf7f-4a66-a25b-74597946764d)

**Comment by Who-are-me** [comment]
> Please attach logs.
> 
> Did you install the 32-bit libraries?

yes
![Screenshot_20240714_140831](https://github.com/user-attachments/assets/38ece327-5189-4533-adb0-ab5504a5474d)

**Comment by iczero** [comment]
I guess opensuse doesn't have ldconfig in the expected location. Thanks for reporting.

**Comment by iczero** [comment]
Fixed in https://github.com/FAForever/faf-linux/commit/839d80e44993eb3deef380b03c6aec54ccdccdb2
