### ISSUE TITLE
ldconfig command not found

### ISSUE THREAD

**Issue by Johni0702** [FAForever/faf-linux#5]
The setup script assumes that the `ldconfig` command is available in the PATH.
However, at least on Debian bullseye, it appears to be installed at `/usr/sbin/ldconfig` which is not by default present in the PATH unless you are root:
```
[...]
looking for libXcomposite.so.1...
./setup.sh: line 166: ldconfig: command not found
```
If I modify that line  to use the absolute path on my machine, setup completes successfully.

It is also missing from the required commands list in the README.

**Comment by iczero** [comment]
`ldconfig` is bundled with glibc and should almost always exist unless you're on an alternate libc like musl. I'll make the check optional anyways.

Can you please check whether PATH includes /usr/sbin in /etc/environment?

**Comment by Johni0702** [comment]
> 

No, that file is empty. `/etc/profile` is where the PATH is set and sbin is included only if you're uid 0:
```sh
if [ "$(id -u)" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH
```
And as per [Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s16.html) it should not be included on any system.
Though it's debatable if ldconfig should be in there. But at least on all recent Debian versions it is: https://packages.debian.org/search?suite=bullseye&arch=any&mode=path&searchon=contents&keywords=ldconfig (`/sbin` is a symlink to `/usr/sbin`)

**Comment by tatsujb** [comment]
hold on your Debian does not have a `/etc/environment` file?

**Comment by Johni0702** [comment]
It exists but it is empty. See also [this StackExchange post about it](https://unix.stackexchange.com/a/85697) and based on [this ticket](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=442049#66) it's been like that since 2008.

**Comment by tatsujb** [comment]
yeah, time to move out of debian, it's showing strong symptoms of abandonment by the devs.
