### ISSUE TITLE
Required libraries not found although they are installed

### ISSUE THREAD

**Issue by BbIXOD** [FAForever/faf-linux#50]
Basically caption.
![image](https://github.com/user-attachments/assets/198b844b-ba86-4850-beff-c42ebec42c88)

**Comment by BbIXOD** [comment]
(and dont look at star at prompt, this terminal does not use nerd fonts and i am to lazy to add it at this term. also)

**Comment by iczero** [comment]
Can you run and attach the output of `ldconfig -p`?

**Comment by BbIXOD** [comment]
> Can you run and attach the output of `ldconfig -p`?

Here is gist with output: https://gist.github.com/BbIXOD/027c1344fd42e09365a0267f01355a09

**Comment by iczero** [comment]
Can you comment out the library check in setup.sh and see if it works? I'm not sure why the 32-bit libraries don't show up in ldconfig in your case.

**Comment by BbIXOD** [comment]
Yes, thanks, it worked, I think I can close this issue
